source "https://rubygems.org"

gem "rails", "~> 8.0"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1"        # For has_secure_password
gem "whenever", require: false # Bonus: cron jobs

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
